home/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('edit/<id>', views.edit, name='edit'),
    path('completado/<id>', views.completado, name='completado'),
    path('delete/<id>', views.delete, name='delete'),
    path('filter/<choice>/', views.filter_prioridad, name='prioridad'),
    path('status/<choice>/', views.filter_status, name='status'),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
]

home/models.py
from django.db import models


class Task(models.Model):
    id = models.BigAutoField(primary_key=True)
    Prioridad = (('B', 'Baja'),
                 ('M', 'Media'),
                 ('A', 'Alta'))

    Nombre_de_la_tarea = models.CharField(max_length=200)
    fecha_de_vencimiento = models.DateTimeField(
        default=None, null=True, blank=True)
    completado = models.BooleanField(default=False)
    prioridad = models.CharField(max_length=1, choices=Prioridad, default='B')

    def __str__(self):
        return self.Nombre_de_la_tarea

home/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from .models import Task
from django.db import models
from django.contrib.auth.models import User


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['Nombre_de_la_tarea', 'fecha_de_vencimiento']
        
    def clean(self):
        cleaned_data = super().clean()
        nombre_tarea = cleaned_data.get('Nombre_de_la_tarea')
        if not nombre_tarea:
            self.add_error('Nombre_de_la_tarea', _(
                'El nombre de la tarea es un campo requerido.'))


class UpdateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['Nombre_de_la_tarea',
                  'fecha_de_vencimiento', 'prioridad', 'completado']

home/views.py
from django.shortcuts import render, redirect
from .models import Task
from .forms import TaskForm, UpdateForm
from django.core.mail import send_mail
from django.utils import timezone
from datetime import datetime, timedelta


def home(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            tarea = form.save(commit=False)
            fecha_vencimiento = form.cleaned_data['fecha_de_vencimiento']
            fecha_vencimiento_dt = datetime.combine(fecha_vencimiento, datetime.min.time()) # Convertir a datetime
            tarea.fecha_vencimiento = timezone.now() + timedelta(days=(fecha_vencimiento_dt - datetime.now()).days)
            tarea.save()

            # Enviar correo electrónico de notificación
            subject = 'Nuevo Mantenimiento Programado'
            message = 'Se ha programado el siguiente mantenimiento "{}" con fecha de vencimiento {}.'.format(tarea.Nombre_de_la_tarea, tarea.fecha_vencimiento.strftime('%d/%m/%Y'))
            from_email = 'centrodecomputos@gmail.com'
            recipient_list = ['emiliojacosta3@gmail.com',]
            send_mail(subject, message, from_email, recipient_list)

            return redirect('home:home')

    tasks = Task.objects.all()
    form = TaskForm()
    print(form)
    return render(request, 'home.html', {'tasks': tasks, 'form': form})


def edit(request, id=id):
    task = Task.objects.get(id=id)
    if request.method == 'POST':
        form = UpdateForm(request.POST or None, instance=task)
        if form.is_valid():
            form.save()
            return redirect('home:home')

    form = UpdateForm(request.POST or None, instance=task)
    print(form)
    return render(request, 'edit.html', {'form': form})


def completado(request, id):
        task = Task.objects.get(id=id)
        if task.completado != True:
            task.completado = True
            tarea_nombre = task.Nombre_de_la_tarea
            
            # Enviar un correo electrónico de notificación
            subject = 'Mantenimiento Completado'
            message = f'El mantenimiento de {tarea_nombre} ha sido completado.'
            from_email = 'centrodecomputos@gmail.com' # Direccion de donde se envia
            recipient_list = ['emiliojacosta3@gmail.com',] # Direccion o direcciones que recibiran el correo
            send_mail(subject, message, from_email, recipient_list)
            task.save()

            return redirect('home:home')


def delete(request, id):
    task = Task.objects.get(id=id)
    task.delete()
    return redirect('home:home')


def filter_prioridad(request, choice):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:home')

    tasks = Task.objects.filter(prioridad=choice)
    form = TaskForm()
    print(form)
    return render(request, 'home.html', {'tasks': tasks, 'form': form})


def filter_status(request, choice):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:home')

    tasks = Task.objects.filter(completado=choice)
    form = TaskForm()
    print(form)
    return render(request, 'home.html', {'tasks': tasks, 'form': form})

templates/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />

    <title>Calendarizacion</title>

    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Add Bootstrap classes-->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"
      integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf"
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Add CSS here -->
    <style>
      body {
        font-family: "Open-Sans", sans-serif;
        line-height: 1.6;
      }
      .add-todo-input {
        outline: None;
      }
      .form-control-lg {
        border-radius: 20px;
      }
      .border-0 {
        border: 1px solid gray !important;
      }
      .btn-primary {
        border-radius: 10px;
        color: #fff;
        background-color: #17a2b8;
        border-color: #17a2b8;
      }
      .rounded {
        border-radius: 1.25rem !important;
      }
      body {
        font-family: "Open-Sans", sans-serif;
        line-height: 1.6;
        background-color: #117a8b;
      }
      .shadow {
        box-shadow: 0 1.5rem 1rem rgba(0, 0, 0, 0.3) !important;
      }
      .bg-light {
        background-color: #ffffff !important;
      }
      .bg-primary {
        background-color: #17a2b8 !important;
      }
      .fa {
        border-radius: 50px;
      }
      .text-primary {
        color: #17a2b8 !important;
      }
    </style>
  </head>
  <body>
    {% block content %} {% endblock %}
  </body>
</html>

templates/edit.html
{% extends 'base.html' %} {% block content %}
<div class="container text-center m-5 p-2 rounded mx-auto bg-light shadow">
  <div class="row m-1 p-4">
    <div class="col">
      <h3 class="card-header bg-info p-3 m-2 text-white">Actualizar Tarea</h3>
      <form method="POST">
        {% csrf_token %} {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Actualizar" />
      </form>
    </div>
  </div>
  {% endblock %}
</div>

templates/home.html
{% extends 'base.html' %} {% block content %}
<div class="container m-5 p-2 rounded mx-auto bg-light shadow">
  <div class="row m-1 p-4">
    <div class="col">
      <div class="p-1 h1 text-primary text-center display-inline-block">
        <i class="fa fa-check bg-primary text-white p-2"></i>
        <u>Mantenimientos</u>
      </div>
    </div> 
  </div>

  <!-- Create form -->
  <form method="POST">
    {% csrf_token %} {% if messages %} {% for message in messages %}
    <div
      class="alert alert-{{ message.tags }} alert-dismissible fade show"
      role="alert"
    >
      {{ message }}
      <button
        type="button"
        class="close"
        data-dismiss="alert"
        aria-label="Close"
      >
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %} {% endif %}

    <div class="row m-1 p-3">
      <div class="col col-11 mx-auto">
        <div class="row bg-white justify-content-center">
          <div class="col">
            <input
              type="text"
              name="Nombre_de_la_tarea"
              maxlength="200"
              required
              id="id_Nombre_de_la_tarea"
              class="form-control form-control-lg border-0 add-todo-input bg-transparent"
              placeholder="Añadir"
            />
          </div>
          <div class="col-auto m-0 px-2 d-flex align-items-center">
            <input
              title="Establece una fecha de vencimiento"
              type="date"
              name="fecha_de_vencimiento"
              id="id_fecha_de_vencimiento"
              lang="es"
            />
          </div>
          <div class="col-auto px-0 mx-0 mr-2 d-flex align-items-center">
            <input type="submit" class="btn btn-primary" value="Añadir" />
          </div>
        </div>
      </div>
    </div>
  </form>

  <div class="p-2 mx-4 border-black-25 border-bottom"></div>

  <!-- Add Task Table -->
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Tarea</th>
        <th scope="col">
          <div class="dropdown">
            <button
              class="btn btn-primary dropdown-toggle"
              type="button"
              data-toggle="dropdown"
            >
              Prioridad
            </button>
            <ul class="dropdown-menu">
              <li>
                <a class="dropdown-item" href="{% url 'home:home' %}">Todas</a>
                <a class="dropdown-item" href="{% url 'home:prioridad' 'B' %}"
                  >Baja</a
                >
                <a class="dropdown-item" href="{% url 'home:prioridad' 'M' %}"
                  >Media</a
                >
                <a class="dropdown-item" href="{% url 'home:prioridad' 'A' %}"
                  >Alta</a
                >
              </li>
            </ul>
          </div>
        </th>
        <th scope="col">Fecha limite</th>
        <th scope="col">
          <div class="dropdown">
            <button
              class="btn btn-primary dropdown-toggle"
              type="button"
              data-toggle="dropdown"
            >
              Estado
            </button>
            <ul class="dropdown-menu">
              <li>
                <a class="dropdown-item" href="{% url 'home:home' %}">Todos</a>
                <a class="dropdown-item" href="{% url 'home:status' 'False' %}"
                  >Pendiente</a
                >
                <a class="dropdown-item" href="{% url 'home:status' 'True' %}"
                  >Completado</a
                >
              </li>
            </ul>
          </div>
        </th>
      </tr>
    </thead>
    <tbody>
      {% for task in tasks %}
      <tr>
        <td scope="row">{{ forloop.counter }}</td>
        <td scope="row">{{ task.Nombre_de_la_tarea }}</td>
        <td scope="row">{{ task.prioridad}}</td>
        <td scope="row">{{ task.fecha_de_vencimiento}}</td>
        <td scope="row">
          {% if task.completado == True %} Completado {% else %}
          <a class="link" href="{% url 'home:completado' task.id %}"
            >Marcar Como Completado</a
          >
          {% endif %}
        </td>
        <td>
          <a href="{% url 'home:edit' task.id %}"
            ><i class="fa fa-edit text-primary"></i
          ></a>
        </td>
        <td>
          <a href="{% url 'home:delete' task.id%}"
            ><i class="fa fa-trash text-danger"></i
          ></a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}